spring:
  redis:
    host: localhost
    port: 6379
    password:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        # 认证中心
        - id: shop-auth
          uri: lb://shop-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        # 商品服务
        - id: shop-goods
          uri: lb://shop-goods
          predicates:
            - Path=/goods/**
        # 用户服务
        - id: shop-user
          uri: lb://shop-user
          predicates:
            - Path=/user/**
        # 订单服务
        - id: shop-order
          uri: lb://shop-order
          predicates:
            - Path=/order/**
        # 日志服务
        - id: shop-logs
          uri: lb://shop-logs
          predicates:
            - Path=/logs/**
        # 文件服务
        - id: shop-file
          uri: lb://shop-file
          predicates:
            - Path=/file/**
          filters:
            - StripPrefix=1

# 安全配置
security:
  ignore:
    # 不校验白名单
    whites:
      - /auth/logout
      - /auth/login
      - /csrf
      - /shop-goods/goods/getById/**
      - /shop-goods/goods/getAll/**
      - /file/**